name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
   APP_NAME: Iface.Oik.ArmStatus

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-restore
    - name: Publish
      run: dotnet publish -c Release --no-restore -r win-x64 --self-contained false -o dist/bin
    - name: Create empty configs folder
      run: mkdir dist/configs
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: $APP_NAME
        path: dist
